# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import restaurant_pb2 as restaurant__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in restaurant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RestaurantServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/restaurant.RestaurantService/Login',
                request_serializer=restaurant__pb2.LoginRequest.SerializeToString,
                response_deserializer=restaurant__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/restaurant.RestaurantService/Logout',
                request_serializer=restaurant__pb2.LogoutRequest.SerializeToString,
                response_deserializer=restaurant__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.GetMenu = channel.unary_unary(
                '/restaurant.RestaurantService/GetMenu',
                request_serializer=restaurant__pb2.MenuRequest.SerializeToString,
                response_deserializer=restaurant__pb2.MenuResponse.FromString,
                _registered_method=True)
        self.UpdatePrice = channel.unary_unary(
                '/restaurant.RestaurantService/UpdatePrice',
                request_serializer=restaurant__pb2.UpdatePriceRequest.SerializeToString,
                response_deserializer=restaurant__pb2.UpdatePriceResponse.FromString,
                _registered_method=True)
        self.CreateOrder = channel.unary_unary(
                '/restaurant.RestaurantService/CreateOrder',
                request_serializer=restaurant__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=restaurant__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.AddItem = channel.unary_unary(
                '/restaurant.RestaurantService/AddItem',
                request_serializer=restaurant__pb2.AddItemRequest.SerializeToString,
                response_deserializer=restaurant__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.RemoveItem = channel.unary_unary(
                '/restaurant.RestaurantService/RemoveItem',
                request_serializer=restaurant__pb2.RemoveItemRequest.SerializeToString,
                response_deserializer=restaurant__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetBill = channel.unary_unary(
                '/restaurant.RestaurantService/GetBill',
                request_serializer=restaurant__pb2.GetBillRequest.SerializeToString,
                response_deserializer=restaurant__pb2.BillResponse.FromString,
                _registered_method=True)
        self.ListOrders = channel.unary_unary(
                '/restaurant.RestaurantService/ListOrders',
                request_serializer=restaurant__pb2.ListOrdersRequest.SerializeToString,
                response_deserializer=restaurant__pb2.ListOrdersResponse.FromString,
                _registered_method=True)
        self.MarkOrderReady = channel.unary_unary(
                '/restaurant.RestaurantService/MarkOrderReady',
                request_serializer=restaurant__pb2.MarkOrderReadyRequest.SerializeToString,
                response_deserializer=restaurant__pb2.MarkOrderReadyResponse.FromString,
                _registered_method=True)
        self.ViewKitchenQueue = channel.unary_unary(
                '/restaurant.RestaurantService/ViewKitchenQueue',
                request_serializer=restaurant__pb2.ViewKitchenQueueRequest.SerializeToString,
                response_deserializer=restaurant__pb2.ViewKitchenQueueResponse.FromString,
                _registered_method=True)
        self.CompleteKitchenItem = channel.unary_unary(
                '/restaurant.RestaurantService/CompleteKitchenItem',
                request_serializer=restaurant__pb2.CompleteKitchenItemRequest.SerializeToString,
                response_deserializer=restaurant__pb2.CompleteKitchenItemResponse.FromString,
                _registered_method=True)
        self.ViewOrder = channel.unary_unary(
                '/restaurant.RestaurantService/ViewOrder',
                request_serializer=restaurant__pb2.ViewOrderRequest.SerializeToString,
                response_deserializer=restaurant__pb2.ViewOrderResponse.FromString,
                _registered_method=True)
        self.Cashout = channel.unary_unary(
                '/restaurant.RestaurantService/Cashout',
                request_serializer=restaurant__pb2.CashoutRequest.SerializeToString,
                response_deserializer=restaurant__pb2.CashoutResponse.FromString,
                _registered_method=True)
        self.ListTables = channel.unary_unary(
                '/restaurant.RestaurantService/ListTables',
                request_serializer=restaurant__pb2.ListTablesRequest.SerializeToString,
                response_deserializer=restaurant__pb2.ListTablesResponse.FromString,
                _registered_method=True)
        self.AddToWaitlist = channel.unary_unary(
                '/restaurant.RestaurantService/AddToWaitlist',
                request_serializer=restaurant__pb2.AddToWaitlistRequest.SerializeToString,
                response_deserializer=restaurant__pb2.AddToWaitlistResponse.FromString,
                _registered_method=True)
        self.ViewWaitlist = channel.unary_unary(
                '/restaurant.RestaurantService/ViewWaitlist',
                request_serializer=restaurant__pb2.ViewWaitlistRequest.SerializeToString,
                response_deserializer=restaurant__pb2.ViewWaitlistResponse.FromString,
                _registered_method=True)
        self.SeatWaitlistParty = channel.unary_unary(
                '/restaurant.RestaurantService/SeatWaitlistParty',
                request_serializer=restaurant__pb2.SeatWaitlistPartyRequest.SerializeToString,
                response_deserializer=restaurant__pb2.SeatWaitlistPartyResponse.FromString,
                _registered_method=True)


class RestaurantServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkOrderReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewKitchenQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteKitchenItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cashout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToWaitlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewWaitlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeatWaitlistParty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=restaurant__pb2.LoginRequest.FromString,
                    response_serializer=restaurant__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=restaurant__pb2.LogoutRequest.FromString,
                    response_serializer=restaurant__pb2.LogoutResponse.SerializeToString,
            ),
            'GetMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMenu,
                    request_deserializer=restaurant__pb2.MenuRequest.FromString,
                    response_serializer=restaurant__pb2.MenuResponse.SerializeToString,
            ),
            'UpdatePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePrice,
                    request_deserializer=restaurant__pb2.UpdatePriceRequest.FromString,
                    response_serializer=restaurant__pb2.UpdatePriceResponse.SerializeToString,
            ),
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=restaurant__pb2.CreateOrderRequest.FromString,
                    response_serializer=restaurant__pb2.CreateOrderResponse.SerializeToString,
            ),
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=restaurant__pb2.AddItemRequest.FromString,
                    response_serializer=restaurant__pb2.OrderResponse.SerializeToString,
            ),
            'RemoveItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveItem,
                    request_deserializer=restaurant__pb2.RemoveItemRequest.FromString,
                    response_serializer=restaurant__pb2.OrderResponse.SerializeToString,
            ),
            'GetBill': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBill,
                    request_deserializer=restaurant__pb2.GetBillRequest.FromString,
                    response_serializer=restaurant__pb2.BillResponse.SerializeToString,
            ),
            'ListOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrders,
                    request_deserializer=restaurant__pb2.ListOrdersRequest.FromString,
                    response_serializer=restaurant__pb2.ListOrdersResponse.SerializeToString,
            ),
            'MarkOrderReady': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkOrderReady,
                    request_deserializer=restaurant__pb2.MarkOrderReadyRequest.FromString,
                    response_serializer=restaurant__pb2.MarkOrderReadyResponse.SerializeToString,
            ),
            'ViewKitchenQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewKitchenQueue,
                    request_deserializer=restaurant__pb2.ViewKitchenQueueRequest.FromString,
                    response_serializer=restaurant__pb2.ViewKitchenQueueResponse.SerializeToString,
            ),
            'CompleteKitchenItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteKitchenItem,
                    request_deserializer=restaurant__pb2.CompleteKitchenItemRequest.FromString,
                    response_serializer=restaurant__pb2.CompleteKitchenItemResponse.SerializeToString,
            ),
            'ViewOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewOrder,
                    request_deserializer=restaurant__pb2.ViewOrderRequest.FromString,
                    response_serializer=restaurant__pb2.ViewOrderResponse.SerializeToString,
            ),
            'Cashout': grpc.unary_unary_rpc_method_handler(
                    servicer.Cashout,
                    request_deserializer=restaurant__pb2.CashoutRequest.FromString,
                    response_serializer=restaurant__pb2.CashoutResponse.SerializeToString,
            ),
            'ListTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTables,
                    request_deserializer=restaurant__pb2.ListTablesRequest.FromString,
                    response_serializer=restaurant__pb2.ListTablesResponse.SerializeToString,
            ),
            'AddToWaitlist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWaitlist,
                    request_deserializer=restaurant__pb2.AddToWaitlistRequest.FromString,
                    response_serializer=restaurant__pb2.AddToWaitlistResponse.SerializeToString,
            ),
            'ViewWaitlist': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewWaitlist,
                    request_deserializer=restaurant__pb2.ViewWaitlistRequest.FromString,
                    response_serializer=restaurant__pb2.ViewWaitlistResponse.SerializeToString,
            ),
            'SeatWaitlistParty': grpc.unary_unary_rpc_method_handler(
                    servicer.SeatWaitlistParty,
                    request_deserializer=restaurant__pb2.SeatWaitlistPartyRequest.FromString,
                    response_serializer=restaurant__pb2.SeatWaitlistPartyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurant.RestaurantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('restaurant.RestaurantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestaurantService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/Login',
            restaurant__pb2.LoginRequest.SerializeToString,
            restaurant__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/Logout',
            restaurant__pb2.LogoutRequest.SerializeToString,
            restaurant__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/GetMenu',
            restaurant__pb2.MenuRequest.SerializeToString,
            restaurant__pb2.MenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/UpdatePrice',
            restaurant__pb2.UpdatePriceRequest.SerializeToString,
            restaurant__pb2.UpdatePriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/CreateOrder',
            restaurant__pb2.CreateOrderRequest.SerializeToString,
            restaurant__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/AddItem',
            restaurant__pb2.AddItemRequest.SerializeToString,
            restaurant__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/RemoveItem',
            restaurant__pb2.RemoveItemRequest.SerializeToString,
            restaurant__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/GetBill',
            restaurant__pb2.GetBillRequest.SerializeToString,
            restaurant__pb2.BillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/ListOrders',
            restaurant__pb2.ListOrdersRequest.SerializeToString,
            restaurant__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkOrderReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/MarkOrderReady',
            restaurant__pb2.MarkOrderReadyRequest.SerializeToString,
            restaurant__pb2.MarkOrderReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewKitchenQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/ViewKitchenQueue',
            restaurant__pb2.ViewKitchenQueueRequest.SerializeToString,
            restaurant__pb2.ViewKitchenQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteKitchenItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/CompleteKitchenItem',
            restaurant__pb2.CompleteKitchenItemRequest.SerializeToString,
            restaurant__pb2.CompleteKitchenItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/ViewOrder',
            restaurant__pb2.ViewOrderRequest.SerializeToString,
            restaurant__pb2.ViewOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cashout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/Cashout',
            restaurant__pb2.CashoutRequest.SerializeToString,
            restaurant__pb2.CashoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/ListTables',
            restaurant__pb2.ListTablesRequest.SerializeToString,
            restaurant__pb2.ListTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToWaitlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/AddToWaitlist',
            restaurant__pb2.AddToWaitlistRequest.SerializeToString,
            restaurant__pb2.AddToWaitlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewWaitlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/ViewWaitlist',
            restaurant__pb2.ViewWaitlistRequest.SerializeToString,
            restaurant__pb2.ViewWaitlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeatWaitlistParty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/SeatWaitlistParty',
            restaurant__pb2.SeatWaitlistPartyRequest.SerializeToString,
            restaurant__pb2.SeatWaitlistPartyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
